### ISSUE TITLE
Ellis exception when trying to create a new number

### ISSUE THREAD

**Issue by AlexHockey** [Metaswitch/ellis#103]
Found when running the live tests against the dogfood deployment. Call stack from the logs is:

```
2015-03-31 10:43:16,930 UTC ERROR _base:172 Uncaught exception POST /accounts/live.tests@example.com/numbers/ (0.0.0.0)
HTTPRequest(protocol='http', host='http_ellis', method='POST', uri='/accounts/live.tests@example.com/numbers/', version='HTTP/1.1', remote_ip='0.0.0.0', body='pstn=false', headers={'Content-Length': '10', 'Cookie': 'Path=/; username="bGl2ZS50ZXN0c0BleGFtcGxlLmNvbQ==|1427798567|add1c425409f8f391ddb1cd15dd3d45fb11bf259"', 'Accept-Encoding': 'gzip, deflate', 'Content-Type': 'application/x-www-form-urlencoded', 'Host': 'http_ellis', 'Accept': '*/*; q=0.5, application/xml', 'User-Agent': 'Ruby'})
Traceback (most recent call last):
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/tornado-2.3-py2.7.egg/tornado/web.py", line 1000, in _stack_context_handle_exception
    raise_exc_info((type, value, traceback))
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/tornado-2.3-py2.7.egg/tornado/web.py", line 1118, in wrapper
    return method(self, *args, **kwargs)
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/ellis-0.1-py2.7.egg/metaswitch/ellis/api/numbers.py", line 182, in post
    public_callback)
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/ellis-0.1-py2.7.egg/metaswitch/ellis/remote/homestead.py", line 162, in create_public_id
    irs = json.loads(resp1.body)['associated_implicit_registration_sets'][0]
IndexError: list index out of range
```

Homestead logs didn't show anything out of the ordinary at the time. 

This then goes onto to leak numbers in Ellis, which are not cleared up at the end of the test:

```
502 Bad Gateway
/var/lib/gems/1.9.1/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:48:in `return!'
/var/lib/gems/1.9.1/gems/rest-client-1.6.7/lib/restclient/request.rb:230:in `process_result'
/var/lib/gems/1.9.1/gems/rest-client-1.6.7/lib/restclient/request.rb:178:in `block in transmit'
/usr/lib/ruby/1.9.1/net/http.rb:745:in `start'
/var/lib/gems/1.9.1/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
/var/lib/gems/1.9.1/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
/var/lib/gems/1.9.1/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
/home/ubuntu/clearwater-live-test/lib/ellis.rb:57:in `destroy_leaked_numbers'
/home/ubuntu/clearwater-live-test/lib/live-test.rb:52:in `run_tests'
/home/ubuntu/clearwater-live-test/Rakefile:39:in `block in <top (required)>'
/var/lib/gems/1.9.1/gems/rake-10.0.3/lib/rake/task.rb:228:in `call'
/var/lib/gems/1.9.1/gems/rake-10.0.3/lib/rake/task.rb:228:in `block in execute'
/var/lib/gems/1.9.1/gems/rake-10.0.3/lib/rake/task.rb:223:in `each'
/var/lib/gems/1.9.1/gems/rake-10.0.3/lib/rake/task.rb:223:in `execute'
/var/lib/gems/1.9.1/gems/rake-10.0.3/lib/rake/task.rb:166:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/1.9.1/gems/rake-10.0.3/lib/rake/task.rb:159:in `invoke_with_call_chain'
/var/lib/gems/1.9.1/gems/rake-10.0.3/lib/rake/task.rb:152:in `invoke'
/var/lib/gems/1.9.1/gems/rake-10.0.3/lib/rake/application.rb:143:in `invoke_task'
/var/lib/gems/1.9.1/gems/rake-10.0.3/lib/rake/application.rb:101:in `block (2 levels) in top_level'
/var/lib/gems/1.9.1/gems/rake-10.0.3/lib/rake/application.rb:101:in `each'
/var/lib/gems/1.9.1/gems/rake-10.0.3/lib/rake/application.rb:101:in `block in top_level'
/var/lib/gems/1.9.1/gems/rake-10.0.3/lib/rake/application.rb:110:in `run_with_threads'
/var/lib/gems/1.9.1/gems/rake-10.0.3/lib/rake/application.rb:95:in `top_level'
/var/lib/gems/1.9.1/gems/rake-10.0.3/lib/rake/application.rb:73:in `block in run'
/var/lib/gems/1.9.1/gems/rake-10.0.3/lib/rake/application.rb:160:in `standard_exception_handling'
/var/lib/gems/1.9.1/gems/rake-10.0.3/lib/rake/application.rb:70:in `run'
/var/lib/gems/1.9.1/gems/rake-10.0.3/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:19:in `load'
/usr/local/bin/rake:19:in `<main>'
/usr/local/bin/ruby_noexec_wrapper:14:in `eval'
/usr/local/bin/ruby_noexec_wrapper:14:in `<main>'
```

**Comment by AlexHockey** [comment]
I found this was affecting about 3 of the live tests per run. I only noticed it on the dogfood system, not on staging.

**Comment by bossmc** [comment]
This happens when the homestead-prov DB has rogue records from previous failed deletes.

On this particular example there's a private ID with no associated IRS.  Ellis assumes that there's always at least 1 IRS and pulls out index `[0]` from the list without checking.

Not sure if this is an Ellis bug, a Homestead-prov bug or both (I think Ellis, as it's probably legit for a private ID to have no IRS/public ID associated with it).

**Comment by graemerobertson** [comment]
We've also hit this when deleting a (presumably corrupted) private ID, although I don't know how the database got into a corrupted state.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/share/clearwater/clearwater-prov-tools/env/lib/python2.7/site-packages/clearwater_prov_tools-0.1-py2.7.egg/metaswitch/ellis/prov_tools/delete_user.py", line 86, in <module>
    main()
  File "/usr/share/clearwater/clearwater-prov-tools/env/lib/python2.7/site-packages/clearwater_prov_tools-0.1-py2.7.egg/metaswitch/ellis/prov_tools/delete_user.py", line 77, in main
    if not utils.delete_user(private_id, public_id, force=args.force):
  File "/usr/share/clearwater/clearwater-prov-tools/env/local/lib/python2.7/site-packages/clearwater_prov_tools-0.1-py2.7.egg/metaswitch/ellis/prov_tools/utils.py", line 193, in delete_user
    homestead.delete_private_id(private_id, callback)
  File "/usr/share/clearwater/clearwater-prov-tools/env/local/lib/python2.7/site-packages/clearwater_prov_tools-0.1-py2.7.egg/metaswitch/ellis/remote/homestead.py", line 136, in delete_private_id
    irs = json.loads(associated_irs_response.body)['associated_implicit_registration_sets'][0]
IndexError: list index out of range
```
