### ISSUE TITLE
Ellis exceptions when Cassandra isn't running

### ISSUE THREAD

**Issue by graemerobertson** [Metaswitch/ellis#113]
Seen on the staging and AIO staging system when Cassandra isn't running (on the Homestead/AIO node).

Obviously Cassandra isn't supposed to not be running, but Ellis shouldn't crash because of it.

```
02-06-2015 11:01:19.860 UTC WARNING homestead.py:276: Passing SIP password in the clear over http
02-06-2015 11:01:39.879 UTC WARNING utils.py:78: Non-OK HTTP response. HTTPResponse(code=599,request_time=40.1296181678772,buffer=None,_body=None,time_info={},request=<tornado.httpclient.HTTPRequest object at 0x2b09c90>,effective_url='http://ec2-54-91-140-86.compute-1.amazonaws.com:7888/org.etsi.ngn.simservs/users/sip%3A6515550538%40example.com/simservs.xml',headers={},error=HTTPError('HTTP 599: Timeout',))
02-06-2015 11:01:39.880 UTC WARNING utils.py:78: Non-OK HTTP response. HTTPResponse(code=599,request_time=40.128255128860474,buffer=None,_body=None,time_info={},request=<tornado.httpclient.HTTPRequest object at 0x2b00cd0>,effective_url='http://ec2-54-91-140-86.compute-1.amazonaws.com:8889/public/sip%3A6515550538%40example.com/associated_private_ids',headers={},error=HTTPError('HTTP 599: Timeout',))
02-06-2015 11:01:39.954 UTC WARNING numbers.py:209: Backed out changes after failure
02-06-2015 11:01:39.955 UTC ERROR web.py:727: Uncaught exception in write_error
Traceback (most recent call last):
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/tornado-2.3-py2.7.egg/tornado/web.py", line 725, in send_error
    self.write_error(status_code, **kwargs)
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/ellis-0.1-py2.7.egg/metaswitch/ellis/api/_base.py", line 345, in write_error
    self.finish(data)
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/tornado-2.3-py2.7.egg/tornado/web.py", line 701, in finish
    self.request.finish()
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/tornado-2.3-py2.7.egg/tornado/httpserver.py", line 433, in finish
    self.connection.finish()
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/tornado-2.3-py2.7.egg/tornado/httpserver.py", line 187, in finish
    self._finish_request()
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/tornado-2.3-py2.7.egg/tornado/httpserver.py", line 223, in _finish_request
    self.stream.read_until(b("\r\n\r\n"), self._header_callback)
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/tornado-2.3-py2.7.egg/tornado/iostream.py", line 153, in read_until
    self._try_inline_read()
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/tornado-2.3-py2.7.egg/tornado/iostream.py", line 381, in _try_inline_read
    self._check_closed()
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/tornado-2.3-py2.7.egg/tornado/iostream.py", line 564, in _check_closed
    raise IOError("Stream is closed")
IOError: Stream is closed
02-06-2015 11:01:39.955 UTC ERROR _base.py:172: Uncaught exception POST /accounts/live.tests.aio.ci@example.com/numbers/ (0.0.0.0)
HTTPRequest(protocol='http', host='http_ellis', method='POST', uri='/accounts/live.tests.aio.ci@example.com/numbers/', version='HTTP/1.1', remote_ip='0.0.0.0', body='pstn=false', headers={'Content-Length': '10', 'Cookie': 'Path=/; username="bGl2ZS50ZXN0cy5haW8uY2lAZXhhbXBsZS5jb20=|1433242399|9febfd42a7b3b989205e802092c7b508e31504fb"', 'Accept-Encoding': 'gzip, deflate', 'Content-Type': 'application/x-www-form-urlencoded', 'Host': 'http_ellis', 'Accept': '*/*; q=0.5, application/xml', 'User-Agent': 'Ruby'})
Traceback (most recent call last):
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/tornado-2.3-py2.7.egg/tornado/web.py", line 1000, in _stack_context_handle_exception
    raise_exc_info((type, value, traceback))
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/tornado-2.3-py2.7.egg/tornado/stack_context.py", line 256, in _nested
    yield vars
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/tornado-2.3-py2.7.egg/tornado/stack_context.py", line 226, in wrapped
    callback(*args, **kwargs)
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/ellis-0.1-py2.7.egg/metaswitch/ellis/api/utils.py", line 61, in callback
    self._check_finished(response)
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/ellis-0.1-py2.7.egg/metaswitch/ellis/api/utils.py", line 81, in _check_finished
    self._failure_callback(response)
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/ellis-0.1-py2.7.egg/metaswitch/ellis/api/numbers.py", line 259, in _on_get_privates_failure
    on_success({})
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/ellis-0.1-py2.7.egg/metaswitch/ellis/api/numbers.py", line 210, in _on_backout_success
    self.forward_error(self.__failure_response)
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/ellis-0.1-py2.7.egg/metaswitch/ellis/api/_base.py", line 290, in forward_error
    detail={"Upstream error": str(code)})
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/ellis-0.1-py2.7.egg/metaswitch/ellis/api/_base.py", line 326, in send_error
    **kwargs)
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/tornado-2.3-py2.7.egg/tornado/web.py", line 729, in send_error
    self.finish()
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/tornado-2.3-py2.7.egg/tornado/web.py", line 700, in finish
    self.flush(include_footers=True)
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/tornado-2.3-py2.7.egg/tornado/web.py", line 651, in flush
    chunk = transform.transform_chunk(chunk, include_footers)
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/tornado-2.3-py2.7.egg/tornado/web.py", line 1735, in transform_chunk
    self._gzip_file.write(chunk)
  File "/usr/lib/python2.7/gzip.py", line 216, in write
    self._check_closed()
  File "/usr/lib/python2.7/gzip.py", line 150, in _check_closed
    raise ValueError('I/O operation on closed file.')
ValueError: I/O operation on closed file.
02-06-2015 11:01:39.956 UTC ERROR web.py:718: Cannot send error response after headers written
02-06-2015 11:01:39.957 UTC WARNING simple_httpclient.py:325: uncaught exception
Traceback (most recent call last):
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/tornado-2.3-py2.7.egg/tornado/simple_httpclient.py", line 323, in cleanup
    yield
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/tornado-2.3-py2.7.egg/tornado/stack_context.py", line 229, in wrapped
    callback(*args, **kwargs)
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/tornado-2.3-py2.7.egg/tornado/simple_httpclient.py", line 234, in _on_timeout
    error=HTTPError(599, "Timeout")))
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/tornado-2.3-py2.7.egg/tornado/simple_httpclient.py", line 318, in _run_callback
    final_callback(response)
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/tornado-2.3-py2.7.egg/tornado/stack_context.py", line 226, in wrapped
    callback(*args, **kwargs)
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/tornado-2.3-py2.7.egg/tornado/stack_context.py", line 271, in _nested
    raise_exc_info(exc)
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/tornado-2.3-py2.7.egg/tornado/stack_context.py", line 263, in _nested
    if exit(*exc):
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/tornado-2.3-py2.7.egg/tornado/stack_context.py", line 161, in __exit__
    return self.exception_handler(type, value, traceback)
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/tornado-2.3-py2.7.egg/tornado/web.py", line 1002, in _stack_context_handle_exception
    self._handle_request_exception(value)
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/ellis-0.1-py2.7.egg/metaswitch/ellis/api/_base.py", line 174, in _handle_request_exception
    self.send_error(500, exc_info=sys.exc_info(), exception=e)
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/ellis-0.1-py2.7.egg/metaswitch/ellis/api/_base.py", line 326, in send_error
    **kwargs)
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/tornado-2.3-py2.7.egg/tornado/web.py", line 720, in send_error
    self.finish()
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/tornado-2.3-py2.7.egg/tornado/web.py", line 700, in finish
    self.flush(include_footers=True)
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/tornado-2.3-py2.7.egg/tornado/web.py", line 651, in flush
    chunk = transform.transform_chunk(chunk, include_footers)
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/tornado-2.3-py2.7.egg/tornado/web.py", line 1735, in transform_chunk
    self._gzip_file.write(chunk)
  File "/usr/lib/python2.7/gzip.py", line 216, in write
    self._check_closed()
  File "/usr/lib/python2.7/gzip.py", line 150, in _check_closed
    raise ValueError('I/O operation on closed file.')
ValueError: I/O operation on closed file.
02-06-2015 11:01:39.958 UTC WARNING utils.py:78: Non-OK HTTP response. HTTP 599: Timeout
02-06-2015 11:01:39.958 UTC WARNING numbers.py:197: Failed to update all the backends
```

**Comment by richardwhiuk** [comment]
Similar stack seen when backend is uncontactable:

```
19-07-2016 15:17:23.170 UTC WARNING numbers.py:217: Backed out changes after failure
19-07-2016 15:17:23.170 UTC ERROR _base.py:171: Uncaught exception POST /accounts/live.tests@example.com/numbers/ (0.0.0.0)
HTTPRequest(protocol='http', host='ellis.rjw2.cw-ngv.com', method='POST', uri='/accounts/live.tests@example.com/numbers/', version='HTTP/1.1', remote_ip='0.0.0.0', body='pstn=false', headers={'Content-Length': '10', 'Cookie': 'username=bGl2ZS50ZXN0c0BleGFtcGxlLmNvbQ==|1468941443|78806d0f3e32836fd9d5998f6b058535c2ff70b0', 'Accept-Encoding': 'gzip, deflate', 'Content-Type': 'application/x-www-form-urlencoded', 'Host': 'ellis.rjw2.cw-ngv.com', 'Accept': '*/*; q=0.5, application/xml', 'User-Agent': 'Ruby'})
Traceback (most recent call last):
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/tornado-2.3-py2.7.egg/tornado/web.py", line 1000, in _stack_context_handle_exception
    raise_exc_info((type, value, traceback))
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/tornado-2.3-py2.7.egg/tornado/stack_context.py", line 256, in _nested
    yield vars
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/tornado-2.3-py2.7.egg/tornado/stack_context.py", line 226, in wrapped
    callback(*args, **kwargs)
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/ellis-0.1-py2.7.egg/metaswitch/ellis/remote/homestead.py", line 284, in callback_wrapper
    callback(response)
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/ellis-0.1-py2.7.egg/metaswitch/ellis/api/utils.py", line 61, in callback
    self._check_finished(response)
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/ellis-0.1-py2.7.egg/metaswitch/ellis/api/utils.py", line 81, in _check_finished
    self._failure_callback(response)
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/ellis-0.1-py2.7.egg/metaswitch/ellis/api/numbers.py", line 267, in _on_get_privates_failure
    on_success({})
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/ellis-0.1-py2.7.egg/metaswitch/ellis/api/numbers.py", line 218, in _on_backout_success
    self.forward_error(self.__failure_response)
```
