### ISSUE TITLE
poll_ellis failures

### ISSUE THREAD

**Issue by rkd-msw** [Metaswitch/ellis#186]
#### Symptoms

Seen on Ellis in EC2 in /var/log/monit.log:

```
[UTC Aug  7 22:44:48] info     : 'poll_etcd_cluster' status succeeded [status=0] -- 0
[UTC Aug  8 00:46:45] error    : 'poll_ellis' '/usr/share/clearwater/bin/poll_ellis.sh' failed with exit status (1) -- HTTP failed to http://10.0.0.90/ping
[UTC Aug  8 00:46:55] error    : 'poll_ellis' '/usr/share/clearwater/bin/poll_ellis.sh' failed with exit status (1) -- HTTP failed to http://10.0.0.90/ping
[UTC Aug  8 00:46:55] info     : 'poll_ellis' exec: /etc/init.d/ellis
[UTC Aug  8 00:47:05] error    : 'ellis_process' process is not running
[UTC Aug  8 00:47:05] info     : 'ellis_process' trying to restart
[UTC Aug  8 00:47:05] info     : 'ellis_process' restart: /etc/monit/run_logged
[UTC Aug  8 00:47:07] error    : 'poll_ellis' '/usr/share/clearwater/bin/poll_ellis.sh' failed with exit status (1) -- HTTP failed to http://10.0.0.90/ping
[UTC Aug  8 00:47:17] info     : 'ellis_process' process is running with pid 23771
[UTC Aug  8 00:51:13] error    : State file '/var/lib/monit/state': Unable to write service state
[UTC Aug  8 01:01:15] error    : 'poll_ellis' '/usr/share/clearwater/bin/poll_ellis.sh' failed with exit status (1) -- HTTP failed to http://10.0.0.90/ping
[UTC Aug  8 01:01:25] error    : 'poll_ellis' '/usr/share/clearwater/bin/poll_ellis.sh' failed with exit status (1) -- HTTP failed to http://10.0.0.90/ping
[UTC Aug  8 01:01:25] info     : 'poll_ellis' exec: /etc/init.d/ellis
[UTC Aug  8 01:01:35] error    : 'ellis_process' process is not running
[UTC Aug  8 01:01:35] info     : 'ellis_process' trying to restart
[UTC Aug  8 01:01:35] info     : 'ellis_process' restart: /etc/monit/run_logged
```

#### Impact

Ellis restarted, so the live tests couldn't create numbers and failed.

#### Release and environment 

'Kangaskhan' release on EC2.

#### Steps to reproduce

???

**Comment by rkd-msw** [comment]
[ellis_20160808T000000Z.txt](https://github.com/Metaswitch/ellis/files/410600/ellis_20160808T000000Z.txt)
[monit.log.txt](https://github.com/Metaswitch/ellis/files/410601/monit.log.txt)

**Comment by graemerobertson** [comment]
We've seen this a lot today on the staging system and @richardwhiuk has expressed an interest in fixing it

**Comment by richardwhiuk** [comment]
Seen once on staging with this at roughly the same time:

```
17-08-2016 19:50:07.964 UTC ERROR ioloop.py:435: Exception in callback <tornado.stack_context._StackContextWrapper object at 0x7f14b5191af8>
Traceback (most recent call last):
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/tornado-2.3-py2.7.egg/tornado/ioloop.py", line 421, in _run_callback
    callback()
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/tornado-2.3-py2.7.egg/tornado/iostream.py", line 304, in wrapper
    callback(*args)
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/tornado-2.3-py2.7.egg/tornado/httpserver.py", line 243, in _on_headers
    remote_ip = self.address[0]
IndexError: string index out of range
```

which looks like https://github.com/tornadoweb/tornado/issues/656

We don't seem to have any nginx logging. The following is configured in /etc/nginx/nginx.config:

```
        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;
```

but `/var/log/nginx/` is empty.

Running ` sudo kill -USR1 ``cat /var/run/nginx.pid`` ` caused them to start appearing...

**Comment by richardwhiuk** [comment]
Right, so what's happening is that we poll ellis every ten seconds, with a timeout of two seconds. Sometimes, these requests timeout because we didn't get a response to ellis. At this point, the client gives up and drops the UNIX socket connection, which may cause the error in Tornado pasted above.

We aren't getting a response from ellis because it's busy doing something else, and we appear to be very single threaded in handling our requests - not sure why this is at the moment - we should be doing things asynchronously.

The something else is normally a connection to the HSS I think - in the example, I have, we had one delete request take 6s to complete - which meant we missed our 2s window.

```
17-08-2016 20:50:02.805 UTC INFO numbers.py:314: Request to delete sip:6515550099@staging.cw-ngv.com by perimeta.live.tests@example.com
17-08-2016 20:50:02.807 UTC INFO homestead.py:273: Sending HTTP GET request to http://hs.staging.cw-ngv.com:8889/public/sip%3A6515550099%40staging.cw-ngv.com/associated_private_ids
17-08-2016 20:50:02.814 UTC INFO homestead.py:273: Sending HTTP GET request to http://hs.staging.cw-ngv.com:8889/private/6515550099%40staging.cw-ngv.com/associated_public_ids
17-08-2016 20:50:02.823 UTC INFO homestead.py:292: Sending HTTP GET request to http://hs.staging.cw-ngv.com:8889/private/6515550099%40staging.cw-ngv.com/associated_implicit_registration_sets
17-08-2016 20:50:02.829 UTC INFO homestead.py:292: Sending HTTP DELETE request to http://hs.staging.cw-ngv.com:8889/irs/0c38907d-5242-4f69-9797-37a3a647026d
17-08-2016 20:50:02.858 UTC INFO homestead.py:273: Sending HTTP DELETE request to http://hs.staging.cw-ngv.com:8889/private/6515550099%40staging.cw-ngv.com
17-08-2016 20:50:02.859 UTC INFO xdm.py:54: Sending HTTP DELETE request to http://homer.staging.cw-ngv.com:7888/org.etsi.ngn.simservs/users/sip%3A6515550099%40staging.cw-ngv.com/simservs.xml
17-08-2016 20:50:02.868 UTC INFO numbers.py:282: Deletion from Homestead and Homer was OK - returning number to pool
17-08-2016 20:50:09.789 UTC INFO web.py:1447: 200 DELETE /accounts/perimeta.live.tests@example.com/numbers/sip%3A6515550099%40staging.cw-ngv.com (0.0.0.0) 6984.12ms
```

These long requests *don't* show up in the logs posted above, because while we are processing them, monit kills ellis and restarts it.

**Comment by richardwhiuk** [comment]
Enabling MySQL slow query logging suggest most of the time is inside MySQL. 

For the following Ellis request:

```
17-08-2016 21:38:31.708 UTC INFO numbers.py:282: Deletion from Homestead and Homer was OK - returning number to pool
17-08-2016 21:38:38.632 UTC INFO web.py:1447: 200 DELETE /accounts/live.tests.ci@example.com/numbers/sip%3A6515550049%40staging.cw-ngv.com (0.0.0.0) 6969.05m
s
```

We see entries of:

```
# Time: 160817 21:38:47
# User@Host: root[root] @ localhost []
# Query_time: 5.223947  Lock_time: 0.000025 Rows_sent: 0  Rows_examined: 1
SET timestamp=1471469927;
UPDATE numbers
                    SET owner_id = NULL
                    WHERE number_id = 'fe17efee-02a2-40d5-a439-b67a755f47f2';
# Time: 160817 21:38:49
# User@Host: root[root] @ localhost []
# Query_time: 2.195542  Lock_time: 0.000000 Rows_sent: 0  Rows_examined: 0
SET timestamp=1471469929;
commit;
```

Next step is to look at the MySQL table to see if it's in a bad way.

**Comment by rkd-msw** [comment]
Any chance that https://github.com/Metaswitch/clearwater-etcd/issues/306 is happening, etcd is using a lot of disk IO, and MySQL isn't getting a chance to write its data to disk (and blocking while it tries)?

That might explain why I saw https://github.com/Metaswitch/clearwater-etcd/issues/307 and https://github.com/Metaswitch/crest/issues/298 at the same time...

**Comment by richardwhiuk** [comment]
Possibly, we see the following pretty constantly:

```
  TID  PRIO  USER     DISK READ  DISK WRITE  SWAPIN     IO>    COMMAND
21005 be/4 clearwat    0.00 B/s   11.79 K/s  0.00 %  0.59 % etcd --listen-client-urls http://10.0.0.90:4000 ~90:2380 --listen-peer-urls http://10.0.0.90:2380
21396 be/4 clearwat    0.00 B/s    7.86 K/s  0.00 %  0.27 % etcd --listen-client-urls http://10.0.0.90:4000 ~90:2380 --listen-peer-urls http://10.0.0.90:2380
```

But doing a run of the live tests, with etcd_process stopped doesn't resolve the problem.

I think our MySQL database is in a really bad shape, which might explain why this appears to be getting worse on the staging server..

Information for the table in question is as follows

````
*************************** 1. row ***************************
           Name: numbers
         Engine: InnoDB
        Version: 10
     Row_format: Compact
           Rows: 110
 Avg_row_length: 148
    Data_length: 16384
Max_data_length: 0
   Index_length: 32768
      Data_free: 12582912
 Auto_increment: NULL
    Create_time: 2015-06-30 12:20:03
    Update_time: NULL
     Check_time: NULL
      Collation: latin1_swedish_ci
       Checksum: NULL
 Create_options:
        Comment:
```

http://serverfault.com/questions/202000/how-find-and-fix-fragmented-mysql-tables suggests a fragmentation percentage of data_free/ (data_length + index_length) gives 256% fragmentation, which is clearly silly.

Attempting to run OPTIMIZE TABLE hangs, even with etcd_process stopped hangs. Create_time is 2015-06-30 12:20:03, so maybe it's best just to kill the schema and recreate it...

**Comment by richardwhiuk** [comment]
Rerunning OPTIMIZE TABLE as `mysqlcheck -u root --optimize ellis numbers` (and `mysqlcheck -u root --optimize ellis users` took 8 hours to complete, but we still see slow queries on the node.

**Comment by richardwhiuk** [comment]
Now tried blasting away the database with `drop database ellis` and `sudo dpkg-reconfigure ellis` to recreate it - we'll see whether that improves things in testing.

**Comment by graemerobertson** [comment]
I've seen this happen again on the same system as before. Here is the relevant section of monit.log.

```
[UTC Aug 26 15:18:17] info     : Awakened by the SIGHUP signal
Reinitializing Monit - Control file '/etc/monit/monitrc'
[UTC Aug 26 15:18:18] info     : 'node-ec2-54-208-204-111.compute-1.amazonaws.com' Monit reloaded
[UTC Aug 26 15:18:34] info     : Awakened by the SIGHUP signal
Reinitializing Monit - Control file '/etc/monit/monitrc'
[UTC Aug 26 15:18:35] info     : 'node-ec2-54-208-204-111.compute-1.amazonaws.com' Monit reloaded
[UTC Aug 26 15:18:46] info     : Awakened by the SIGHUP signal
Reinitializing Monit - Control file '/etc/monit/monitrc'
[UTC Aug 26 15:18:46] info     : 'node-ec2-54-208-204-111.compute-1.amazonaws.com' Monit reloaded
[UTC Aug 26 15:18:46] error    : 'snmpd_process' process is not running
[UTC Aug 26 15:18:46] info     : 'snmpd_process' trying to restart
[UTC Aug 26 15:18:46] info     : 'snmpd_process' start: /bin/bash
[UTC Aug 26 15:18:57] info     : 'snmpd_process' process is running with pid 11810
[UTC Aug 26 15:20:47] error    : 'poll_etcd_cluster' '/usr/share/clearwater/bin/poll_etcd_cluster.sh' failed with exit status (1) -- zmq_msg_recv: Resource temporarily unavailable
1
[UTC Aug 26 15:21:38] error    : 'poll_ellis' '/usr/share/clearwater/bin/poll_ellis.sh' failed with exit status (1) -- HTTP failed to http://10.0.0.90/ping
[UTC Aug 26 15:21:48] error    : 'poll_ellis' '/usr/share/clearwater/bin/poll_ellis.sh' failed with exit status (1) -- HTTP failed to http://10.0.0.90/ping
[UTC Aug 26 15:21:48] info     : 'poll_ellis' exec: /etc/init.d/ellis
[UTC Aug 26 15:21:48] error    : 'poll_etcd_cluster' '/usr/share/clearwater/bin/poll_etcd_cluster.sh' failed with exit status (1) -- 1
[UTC Aug 26 15:21:58] error    : 'ellis_process' process is not running
[UTC Aug 26 15:21:58] info     : 'ellis_process' trying to restart
[UTC Aug 26 15:21:58] info     : 'ellis_process' restart: /etc/monit/run_logged
[UTC Aug 26 15:21:58] error    : 'poll_ellis' '/usr/share/clearwater/bin/poll_ellis.sh' failed with exit status (1) -- HTTP failed to http://10.0.0.90/ping
[UTC Aug 26 15:22:08] info     : 'ellis_process' process is running with pid 12357
[UTC Aug 26 15:22:56] error    : 'poll_etcd_cluster' '/usr/share/clearwater/bin/poll_etcd_cluster.sh' failed with exit status (1) -- 1
[UTC Aug 26 15:23:58] info     : 'poll_etcd_cluster' status succeeded [status=0] -- zmq_msg_recv: Resource temporarily unavailable
0
```
