### ISSUE TITLE
sync_database.py fails due to missing pycurl dependancy

### ISSUE THREAD

**Issue by richardwhiuk** [Metaswitch/ellis#188]
#### Symptoms

Running ```
cd /usr/share/clearwater/ellis
sudo env/bin/python src/metaswitch/ellis/tools/sync_databases.py
``` as documented at http://clearwater.readthedocs.io/en/stable/Backups.html fails with:

```
[ellis-1]ubuntu@ec2-54-237-248-91:/usr/share/clearwater/ellis$ sudo env/bin/python src/metaswitch/ellis/tools/sync_databases.py
Traceback (most recent call last):
  File "src/metaswitch/ellis/tools/sync_databases.py", line 54, in <module>
    max_clients=100)
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/tornado-2.3-py2.7.egg/tornado/httpclient.py", line 209, in configure
    impl = import_object(impl)
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/tornado-2.3-py2.7.egg/tornado/util.py", line 30, in import_object
    obj = __import__('.'.join(parts[:-1]), None, None, [parts[-1]], 0)
  File "/usr/share/clearwater/ellis/env/local/lib/python2.7/site-packages/tornado-2.3-py2.7.egg/tornado/curl_httpclient.py", line 24, in <module>
    import pycurl
ImportError: No module named pycurl
```

#### Impact

Unable to run the sync_database.py script which is required as part of restoring a backup

#### Release and environment 

Latest code - e4727329dee7f3db4471d97413c8746d87b39a65 - on Amazon EC2 deployed via Chef

#### Steps to reproduce

Install an ellis node via chef.

Run the above commands to sync the database.

**Comment by richardwhiuk** [comment]
I was able to get through this hurdle by running `sudo apt-get install libcurl4-openssl-dev` and then `sudo env/bin/pip install pycurl` - but we should really be packaging pycurl as a dependancy.
